created exchangeRates endpoint
EdgeApp/edge-rates-server pull request #18
Opened 2020-12-31 19:15 UTC by thomasgonda3

![exchangeRatesEndpoint](https://user-images.githubusercontent.com/64434651/103423053-714d5c80-4b59-11eb-8a17-5835d787c06d.PNG)

2021-01-13 08:04 UTC, thehobbit85 requested changes

2021-01-13 08:04 UTC, thehobbit85 commented on src/index.ts
> +  res.json(await getExchangeRate(req.query, dbRates))
you need to "try-catch" here and return correct status code if error similar to what you are doing in "exchangeRates"

2021-01-27 18:01 UTC, thomasgonda3 commented on src/index.ts
> +  const returnedRates: ReturnRate[] = []
create promise.all instead of for loop

2021-01-27 18:06 UTC, thehobbit85 approved these changes

2021-01-27 18:06 UTC, merged