Convert /exchangeRates endpoint to use bulk queries to data providers
EdgeApp/edge-rates-server pull request #33
Opened 2021-05-24 05:57 UTC by peachbits

This commit overhauls the rates server to use bulk data endpoints.

- The following historical data endpoints are now batching requests
  coinmarketcap
  currencyconverter
  openexchangerates (new backup fiat data source)

- The following latest data endpoints are now batching requests
  coinmarketcap
  coincap
  nomics (new)
  compound (new)

Coincap historical doesn't not support batching so those are still single requests. The zero and fallback rates are also techincally bulk now as well.

Other changes:
- Use async-lock to prevent multiple writes to the same document.
- Each requested rate obj can include a date.
- Partially added Edge-preferred unique IDs. This takes the map of currency codes and unique IDs from a data source and ensures the default currencies in Edge the queried values in case of duplicates. Only using it for coincap and it does not dynamically refresh the original list of 2000.
- Currency bridge uses bridge currencies to connect to two existing rates to find a third unknown rate (ie. requested BCH_JPY, can return a rate with BCH_USD and JPY_USD). This is synchronous and doesn't create new queries to data providers.
- Crypto data providers now only query rates against USD. Fiat data providers will query against USD.
- Currencies pegged to an underlying asset (ie. WETH, AUSDC, etc) use the underlying asset price.
- Updated /exchangeRate endpoint to use new request code.

2021-06-08 01:43 UTC, peachbits commented on src/providers/coinMarketCapBasic.ts
> +        `https://pro-api.coinmarketcap.com/v1/cryptocurrency/quotes/latest?symbol=${codes}&skip_invalid=true`,
no literal

2021-06-08 01:43 UTC, peachbits commented on src/providers/coincap.ts
> +        const url = `https://api.coincap.io/v2/assets?ids=${codes}`
no literal

2021-06-08 01:43 UTC, peachbits commented on src/providers/coincap.ts
> +    for (const date in datesAndCodesWanted) {
promise.all

2021-06-08 01:43 UTC, peachbits commented on src/providers/coincap.ts
> +        for (const code of datesAndCodesWanted[date]) {
promise.all

2021-06-08 01:43 UTC, peachbits commented on src/providers/coincap.ts
> +              `https://api.coincap.io/v2/assets/${id}/history?interval=m1&start=${timestamp}&end=${timestamp +
no literal

2021-06-08 01:43 UTC, peachbits commented on src/providers/coincap.ts
> +      if (date === currentTime) {
separate current and historical functions

2021-06-08 01:43 UTC, peachbits commented on src/providers/currencyConverter.ts
> +  for (const date in datesAndCodesWanted) {
promise.all

2021-06-08 01:43 UTC, peachbits commented on src/providers/currencyConverter.ts
> +      for (const pair of Object.keys(results)) {
standardize

2021-06-08 01:43 UTC, peachbits commented on src/providers/currencyConverter.ts
> +      for (const pair of Object.keys(results)) {
Object.assign(rates, Object.keys(results).reduce((rates, pair)=> ({...rates, [pair]:results[pair].val[justDate].toString()}), {}))

2021-06-08 01:43 UTC, peachbits commented on src/providers/openExchangeRates.ts
> +  for (const date in datesAndCodesWanted) {
promise.all

2021-06-11 04:25 UTC, thehobbit85 requested changes
See comments

2021-06-11 04:25 UTC, thehobbit85 commented on src/config.ts
> +  ),
Create a config param like this:
```
providers: {
   currencyConverter: {
       uri: *****,
       apiKey: ****
   }
 }
 ```

2021-06-11 04:25 UTC, thehobbit85 commented on src/providers/openExchangeRates.ts
> +  )
This is not how you should convert this into Promise.all.
Let's have a sidebar and I'll show you how it should be done.

2021-06-22 17:52 UTC, peachbits commented on src/providers/coincap.ts
> +    const json = asCoincapCurrentResponse(await response.json())
normalize response and create shared function

2021-07-20 20:39 UTC, merged