Use "iso:" prefix for fiat currency codes
EdgeApp/edge-rates-server pull request #45
Opened 2021-06-14 07:34 UTC by peachbits

2021-06-23 20:22 UTC, peachbits commented on src/config.ts
>    httpPort: asOptional(asNumber, 8008),
add iso:USD constant

2021-06-23 20:22 UTC, peachbits commented on src/config.ts
>    fiatCurrencyCodes: asOptional(asArray(asString), [
add to config "DEFAULT_FIAT_CODE"

2021-06-23 20:22 UTC, peachbits commented on src/utils/currencyCodeMaps.ts
>    FORK: true
Make json

2021-06-23 20:22 UTC, peachbits commented on src/utils/currencyCodeMaps.ts
> +  'SAI_iso:USD': '1',
create function to add isos to constants

2021-06-25 03:47 UTC, thehobbit85 requested changes
See comments.

2021-06-25 03:47 UTC, thehobbit85 commented on src/providers/coinMarketCap.ts
> +        rates[date][`${code}_${DEFAULT_FIAT}`] = json.data[
Create and use the function everywhere in the code:
```
const defualtFiatPair = (code) => `${code}_${DEFAULT_FIAT}`
```

2021-06-25 03:47 UTC, thehobbit85 commented on src/providers/currencyConverter.ts
>        datesAndCodesWanted[pair.date].indexOf(`${subIso(fromCurrency)}_USD`) ===
This can be something like `${subIso(fromCurrency)}_${subIso(DEFAULT_FIAT)}` no?

2021-07-29 00:35 UTC, peachbits commented on src/providers/coinMarketCap.ts
> +): string => data[code].quotes[0].quote[subIso(DEFAULT_FIAT)].price.toString()
dont use specific key in array. use an array method or ?

2021-07-29 03:54 UTC, thehobbit85 requested changes
Some type fixing

2021-07-29 03:54 UTC, thehobbit85 commented on src/utils/utils.ts
> +) => (data: any[]): RateMap =>
Instead of typing any, use generics:
```<T>(data: T[]): RateMap =>....```

2021-07-29 03:54 UTC, thehobbit85 commented on src/utils/utils.ts
> +) => (data): RateMap =>
use generics, I think this can work, not 100% sure ;)

```<T extends {}>(data: T): RateMap =>....```

2021-08-11 23:53 UTC, thehobbit85 commented
/rebase-autosquash

2021-08-11 23:54 UTC, merged