Add unique ID maps and engine
EdgeApp/edge-rates-server pull request #54
Opened 2021-07-28 18:27 UTC by peachbits

2021-08-06 19:50 UTC, peachbits commented on src/rates.ts
> +    const docs: string[] = ['currencyCodeMaps']
Don't get with every call. Memoize instead

2021-08-06 19:50 UTC, peachbits commented on src/providers/coinMarketCap.ts
> +export const invertCodeMapKey = (id: string, assetMap: AssetMap): string => {
one-liner

2021-08-06 19:50 UTC, peachbits commented on src/providers/coinMarketCap.ts
> +      !DEFAULT_CODES.includes(fromCurrency) &&
remove this

2021-08-06 19:50 UTC, peachbits commented on src/rates.ts
> +  let constantCurrencyCodes = {}
Pass relevant asset map

2021-08-06 19:50 UTC, peachbits commented on src/utils/dbUtils.ts
> +  localDB
add simple rev based conflict resolution. Keep highest

2021-08-06 22:04 UTC, thehobbit85 requested changes
Changes!

2021-08-06 22:04 UTC, thehobbit85 commented on package.json
>    },
Change!

2021-08-13 02:08 UTC, thehobbit85 requested changes

2021-08-13 04:37 UTC, merged